//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUF_FMODR
    {
        public int RefNo { get; set; }
        public string FundID { get; set; }
        public string ProductID { get; set; }
        public string BSFlag { get; set; }
        public string LSFlag { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public string FMID { get; set; }
        public string Reason { get; set; }
        public string Strategy { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Tgtwgt { get; set; }
        public string OdrType { get; set; }
        public string Style { get; set; }
        public Nullable<int> Priority { get; set; }
        public string CD { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public string ActType { get; set; }
        public string PnoteIssuer { get; set; }
        public string AllocationMode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> fundbal { get; set; }
        public string bypass { get; set; }
        public string basketname { get; set; }
        public Nullable<decimal> cshholdpct { get; set; }
        public Nullable<int> OdrNo { get; set; }
        public Nullable<int> qtyErrFlag { get; set; }
    }
}
