//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBF_ORDER_REASON
    {
        public int seq { get; set; }
        public string Reason { get; set; }
        public string Updateby { get; set; }
        public System.DateTime UpdateOn { get; set; }
    }
}
