//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRONT_BAL_PORTFOLIO
    {
        public int Seq { get; set; }
        public string Type { get; set; }
        public string FundID { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> ValQty { get; set; }
        public Nullable<decimal> ValPrice { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public string ProdCCY { get; set; }
        public string FundCCY { get; set; }
        public Nullable<decimal> FxRate { get; set; }
        public string ProdType { get; set; }
        public Nullable<decimal> ProdTypeMultiplier { get; set; }
        public Nullable<decimal> ProdMrgn { get; set; }
        public string GLType { get; set; }
        public Nullable<decimal> ProdBal_ProdCCY { get; set; }
        public Nullable<decimal> ProdCost_ProdCCY { get; set; }
        public Nullable<decimal> ProdBal_FundCCY { get; set; }
        public Nullable<decimal> ProdCost_FundCCY { get; set; }
        public Nullable<decimal> FundBal { get; set; }
        public Nullable<decimal> FundCost { get; set; }
        public string CoCode { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    }
}
