//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRONT_DBF_FUND
    {
        public string FundID { get; set; }
        public string ShortName { get; set; }
        public string FundName { get; set; }
        public string FundMgr { get; set; }
        public string RebateFlag { get; set; }
        public Nullable<decimal> LastPfmPrice { get; set; }
        public Nullable<decimal> NAV { get; set; }
        public Nullable<int> ValFreq { get; set; }
        public string ValFreqUnit { get; set; }
        public string ValWithinMth { get; set; }
        public Nullable<System.DateTime> NextValDate { get; set; }
        public Nullable<System.DateTime> FinYrEnd { get; set; }
        public string Remark { get; set; }
        public string TimeStmp { get; set; }
        public string ChkStoredPrc { get; set; }
        public Nullable<System.DateTime> LaunchDate { get; set; }
        public string CCY { get; set; }
        public string Auditor { get; set; }
        public Nullable<int> AvgUnitFreq { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<System.DateTime> LastValDate { get; set; }
        public Nullable<int> YrDays { get; set; }
        public Nullable<decimal> HWM { get; set; }
        public Nullable<decimal> HurdleRate { get; set; }
        public string HurdleRatePct { get; set; }
        public Nullable<int> UnitDec { get; set; }
        public string UnitDecDir { get; set; }
        public Nullable<decimal> GrossNAV { get; set; }
        public Nullable<decimal> FundCost { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string UnitFlag { get; set; }
        public string FundAlias { get; set; }
        public Nullable<decimal> FundBal { get; set; }
        public Nullable<System.DateTime> FirstDDay { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CoCode { get; set; }
        public Nullable<decimal> ReqLong { get; set; }
        public Nullable<decimal> ReqShort { get; set; }
        public string AllowBL { get; set; }
        public string MPFFlag { get; set; }
        public Nullable<decimal> TargetCash { get; set; }
        public string SecACNo { get; set; }
        public string SecACName { get; set; }
        public string SecACBank { get; set; }
        public string SecAC2No { get; set; }
        public string SecAC2Name { get; set; }
        public string SecAC2Bank { get; set; }
        public string PPtACNo { get; set; }
        public string PPtACName { get; set; }
        public string PPtACBank { get; set; }
        public string primbkr { get; set; }
        public Nullable<decimal> putThruRate { get; set; }
        public string FundType { get; set; }
        public string CustFee { get; set; }
        public string ManageApproach { get; set; }
        public string Autoselect { get; set; }
    }
}
