//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Fund_FrontEndEntities : DbContext
    {
        public Fund_FrontEndEntities()
            : base("name=Fund_FrontEndEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FRONT_DBF_FUND> FRONT_DBF_FUND { get; set; }
        public DbSet<DBF_ORDER_REASON> DBF_ORDER_REASON { get; set; }
        public DbSet<DBF_ORDER_STRATEGY> DBF_ORDER_STRATEGY { get; set; }
        public DbSet<LOG_FMODR_ERROR> LOG_FMODR_ERROR { get; set; }
        public DbSet<TRN_FMODR> TRN_FMODR { get; set; }
        public DbSet<BUF_FMODR> BUF_FMODR { get; set; }
        public DbSet<FRONT_ADM_USERFUND> FRONT_ADM_USERFUND { get; set; }
        public DbSet<FRONT_DBF_PRODUCT> FRONT_DBF_PRODUCT { get; set; }
        public DbSet<v_ORDER_FORM_RESULT> v_ORDER_FORM_RESULT { get; set; }
        public DbSet<FRONT_BAL_PORTFOLIO> FRONT_BAL_PORTFOLIO { get; set; }
        public DbSet<v_QRY_FUND_CASH> v_QRY_FUND_CASH { get; set; }
        public DbSet<v_QRY_FUND_CASH_TWD> v_QRY_FUND_CASH_TWD { get; set; }
    
        public virtual int sp_cal_fmodr_v2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cal_fmodr_v2");
        }
    
        public virtual int sp_sys_email_alert_fm(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sys_email_alert_fm", userIDParameter);
        }
    
        public virtual int sp_sys_email_alert_ss(string stage)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("Stage", stage) :
                new ObjectParameter("Stage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sys_email_alert_ss", stageParameter);
        }
    
        public virtual int sp_ins_fmodr_v2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_fmodr_v2");
        }
    }
}
