//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRONT_DBF_PRODUCT
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public string Industry { get; set; }
        public string ExchID { get; set; }
        public string CCY { get; set; }
        public string CtryCode { get; set; }
        public string ISIN { get; set; }
        public string SEDOLL { get; set; }
        public string CashType { get; set; }
        public Nullable<int> VotePerShare { get; set; }
        public Nullable<decimal> ClsPrice { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public Nullable<decimal> ClsBid { get; set; }
        public Nullable<decimal> ClsAsk { get; set; }
        public Nullable<decimal> ChgPct { get; set; }
        public Nullable<decimal> IssuedShare { get; set; }
        public string Stamp { get; set; }
        public string Levy { get; set; }
        public string Suspend { get; set; }
        public string CCASS { get; set; }
        public string TradeFee { get; set; }
        public string SettleFee { get; set; }
        public string SSEFee { get; set; }
        public string AdminFee { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public Nullable<System.DateTime> RestrictFmDate { get; set; }
        public Nullable<System.DateTime> RestrictToDate { get; set; }
        public string CCYQuote { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> LotSize { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> DecPt { get; set; }
        public Nullable<decimal> PrevClsPrice { get; set; }
        public string TfrFee { get; set; }
        public string IssuedShareUPD { get; set; }
        public string UnitType { get; set; }
        public string Rel_ProductID { get; set; }
        public Nullable<decimal> TxVolDaily { get; set; }
        public Nullable<decimal> TxVolAvg { get; set; }
        public Nullable<decimal> MgtStake { get; set; }
        public Nullable<decimal> TotHold { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> PriceFactor { get; set; }
        public string Short { get; set; }
        public string TickExempt { get; set; }
        public string ExtProdType { get; set; }
        public string FullyPaidUp { get; set; }
        public string Issuer { get; set; }
        public string IPODate { get; set; }
        public Nullable<decimal> MktCap { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<decimal> vwap { get; set; }
        public Nullable<decimal> sd { get; set; }
        public string collateral { get; set; }
        public string cntryofrisk { get; set; }
    }
}
