//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRONT_ADM_USERFUND
    {
        public string UserID { get; set; }
        public string FundID { get; set; }
        public int Seq { get; set; }
        public string TimeStmp { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
