//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_FMODR
    {
        public int OdrNo { get; set; }
        public Nullable<int> GrpNo { get; set; }
        public Nullable<System.DateTime> OdrTime { get; set; }
        public string FMID { get; set; }
        public string TraderID { get; set; }
        public string FundID { get; set; }
        public string ProductID { get; set; }
        public string BSFlag { get; set; }
        public string ProdCCY { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public string Pct { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Style { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string TimeStmp { get; set; }
        public Nullable<decimal> cOdrPrice { get; set; }
        public Nullable<decimal> cOdrQty { get; set; }
        public Nullable<decimal> cUpToQty { get; set; }
        public string cBSFlag { get; set; }
        public Nullable<decimal> cTotFillQty { get; set; }
        public Nullable<decimal> cTotCanQty { get; set; }
        public string cOdrFlag { get; set; }
        public string cOdrStatus { get; set; }
        public string Posted { get; set; }
        public string Reason { get; set; }
        public string Strategy { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public string LSFlag { get; set; }
        public string Callable { get; set; }
        public string Email { get; set; }
        public string DocRefNo { get; set; }
        public string AllocationMode { get; set; }
        public string OdrType { get; set; }
        public string InputBy { get; set; }
        public Nullable<bool> Hedging { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string CD { get; set; }
        public string OdrOwner { get; set; }
        public string Hold { get; set; }
        public string HoldReason { get; set; }
        public Nullable<decimal> cshholdpct { get; set; }
        public Nullable<int> CshHoldPctFlag { get; set; }
        public string ActType { get; set; }
        public string BasketName { get; set; }
        public string BasketApproved { get; set; }
        public string IPOType { get; set; }
        public string ProdRef { get; set; }
        public string PNoteIssuer { get; set; }
        public string Onbehalf { get; set; }
    }
}
