//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPFS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_QRY_FUND_CASH
    {
        public string fundalias { get; set; }
        public string fundccy { get; set; }
        public Nullable<decimal> fundbal { get; set; }
        public Nullable<decimal> cashonhand { get; set; }
        public Nullable<decimal> pendcash { get; set; }
        public Nullable<decimal> cashremained { get; set; }
        public string userid { get; set; }
        public string fundid { get; set; }
    }
}
